#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      authentication-database: admin
      database: photo-customer
      username: root
      password: ''
      port: 27017
      host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/