#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      #authentication-database: admin
      database: photo-customer
      username: jsrz_pragma
      password: jsmithr
      port: '27017'
      host: practicecustomer-shard-00-01.kudgh.mongodb.net
#spring:
#  data:
#    mongodb:
#      database: spring-boot-project-mongodb-photos-database
#      username: root
#      password: crissjazz98 # >:v
#      port: '27017'
#      host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/