#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      authentication-database: admin
      username: jsrz_pragma
      password: jsmithr
      database: photo-customer
      host: practicecustomer.kudgh.mongodb.net
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/