#jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_dad68ecddd28957
#jdbc.username=b836d9d3793cb6
#jdbc.password=b46346a5

#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_1eed9fc9e4924b9
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: b79c6d842bcdd0
    password: 2992dd6f

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"